### ISSUE TITLE
design the login page

### ISSUE THREAD

**Issue by nityanandagohain** [nityanandagohain/keep_clone#1]

**Comment by stormfireuttam** [comment]
can you describe what all details you need on the login page

**Comment by nityanandagohain** [comment]
Currently, the design is basic and only login with email and password is available. So you can you material design for the home page.

**Comment by thebishaldeb** [comment]
I want to work on this.

**Comment by nityanandagohain** [comment]
Sure go ahead.

**Comment by nityanandagohain** [comment]
I am keeping this issue open. So that the design can be improved more.
