### ISSUE TITLE
Design the card to enter notes.

### ISSUE THREAD

**Issue by nityanandagohain** [nityanandagohain/keep_clone#16]
The design for inserting notes is pretty basic. Design a card with the title, desc and add button for the homepage.

**Comment by rajghosh2000** [comment]
i would like to try this

**Comment by nityanandagohain** [comment]
go ahead

**Comment by Arp-1** [comment]
What exactly we have to do? Do we have to enable editing for prestored notes?

**Comment by nityanandagohain** [comment]
This issue is for just design Notes entering the section. Enabling editing for stored notes will be a new issue.
