### ISSUE TITLE
Design card to display notes.

### ISSUE THREAD

**Issue by nityanandagohain** [nityanandagohain/keep_clone#17]
Design proper card to display the notes.

**Comment by subhasishgosw5** [comment]
interested in doing it

**Comment by nityanandagohain** [comment]
go ahead.

**Comment by thebishaldeb** [comment]
Taking it

**Comment by Tyak99** [comment]
Why is it reopened?

**Comment by nityanandagohain** [comment]
There is room for improvement .

**Comment by sinharaksh1t** [comment]
Interested in taking on this issue as first time contribution.

**Comment by nityanandagohain** [comment]
go ahead @sinharaksh1t
