### ISSUE TITLE
add option to draw on notes

### ISSUE THREAD

**Issue by nityanandagohain** [nityanandagohain/keep_clone#2]

**Comment by PseudoNerd** [comment]
Do we need to add a writing space here for manual input and recognize the text or is it something else entirely?

**Comment by nityanandagohain** [comment]
We need to add writing/drawing space that will be on a canvas then convert the png to base64 and send store it in firebase. also, fetch the basee64 data convert back to the image.

**Comment by thebishaldeb** [comment]
I would like to try this out.

**Comment by nityanandagohain** [comment]
@PseudoNerd are you working on this?

**Comment by Arp-1** [comment]
Would like to work on it!

**Comment by nityanandagohain** [comment]
go ahead @Arp-1
