### ISSUE TITLE
Improve the design of the homepage

### ISSUE THREAD

**Issue by nityanandagohain** [nityanandagohain/keep_clone#4]
Improve the design you can use libraries or write your own css.

**Comment by stormfireuttam** [comment]
I would like to work on your project

**Comment by nityanandagohain** [comment]
Sure :)

**Comment by PseudoNerd** [comment]
Would like to work on this.

**Comment by nityanandagohain** [comment]
@PseudoNerd since @stormfireuttam commented first you can work on some other issue.

**Comment by nityanandagohain** [comment]
@stormfireuttam updates?

**Comment by Sshruti10** [comment]
I would like to work on the project.

**Comment by Stantonator93** [comment]
Am I allowed to go all out and just overhaul the whole design? For example, colours, fonts, layout etc?
I think the whole thing could use a bit of love when it comes to the CSS
