### ISSUE TITLE
Implement drag and drop

### ISSUE THREAD

**Issue by nityanandagohain** [nityanandagohain/keep_clone#44]
Implement drag and drop to organize notes.

Here is an article https://medium.com/@alexandereardon/rethinking-drag-and-drop-d9f5770b4e6b

**Comment by singhrohan62** [comment]
Hey @nityanandagohain , I would like to work on adding this feature

**Comment by Hector-Ariceaga** [comment]
I would love to try my hand at this! Do you have a preference for which library you want to utilize to add this feature? The Medium article refers specifically to react-beautiful-dnd.

**Comment by nityanandagohain** [comment]
Sure, that will be great. I would suggest you to use react-beautiful-dnd but if you know something better you can definitely use it.
